ktor:
  application:
    modules:
      - com.bittokazi.ktor.gateway.ApplicationKt.module
  deployment:
    port: 5035

proxy:
  enabled: true
  gateway-oauth-base-path: "/gw"
  session-validity-in-seconds: 60
  routes:
    "": #blank means default/any domain will match
      - prefix: /api
        target: http://127.0.0.1:8081
        authType: TOKEN_BASED
      - prefix: /public/api
        target: http://127.0.0.1:8081
      - prefix: /oauth
        target: http://127.0.0.1:8081
      - prefix: /app-cpanel-static
        target: http://127.0.0.1:8081
      - prefix: /health
        target: http://127.0.0.1:8081
      - prefix: /swagger
        target: http://127.0.0.1:8081
      - prefix: /app
        target: http://127.0.0.1:3039
      - prefix: /static
        target: http://127.0.0.1:3039
    "example.com":
      - prefix: /
        target: http://192.168.10.1
        authType: SESSION_BASED
      - prefix: /cgi-bin
        target: http://192.168.10.1
        authType: SESSION_BASED
      - prefix: /luci-static
        target: http://192.168.10.1
        authType: SESSION_BASED
    "example1.com":
      - prefix: /
        target: http://192.168.10.1
        secure: true
  oauth-clients:
    "": #blank means default/any domain will match
      clientId: "api-client"
      clientSecret: "secret"
      scopes:
        - openid
        - profile
        - email
      authorizeUrl: "http://localhost:8081/oauth/authorize"
      tokenUrl: "http://localhost:8081/oauth/token"
      introspectUrl: "http://localhost:8081/oauth/introspect"
      logoutUrl: "http://localhost:8081/oauth/logout"
    "example1.com":
      clientId: "api-client"
      clientSecret: "secret"
      scopes:
        - openid
        - profile
        - email
      authorizeUrl: "http://localhost:8081/oauth/authorize"
      tokenUrl: "http://localhost:8081/oauth/token"
      introspectUrl: "http://localhost:8081/oauth/introspect"
      logoutUrl: "http://localhost:8081/oauth/logout"
