ktor:
  application:
    modules:
      - com.bittokazi.ktor.gateway.ApplicationKt.module
  deployment:
    port: 5035

proxy:
  enabled: true
  gateway-oauth-base-path: "/gw"
  session-validity-in-seconds: 60
#  routes:
#    - prefix: /
#      target: http://192.168.10.1
#      secure: true
#    - prefix: /cgi-bin
#      target: http://192.168.10.1
#      secure: true
#    - prefix: /luci-static
#      target: http://192.168.10.1
#      secure: true
  routes:
    "": #blank means default/any domain will match
      - prefix: /api
        target: http://127.0.0.1:8081
      - prefix: /oauth
        target: http://127.0.0.1:8081
      - prefix: /app-cpanel-static
        target: http://127.0.0.1:8081
      - prefix: /health
        target: http://127.0.0.1:8081
      - prefix: /swagger
        target: http://127.0.0.1:8081
      - prefix: /app
        target: http://127.0.0.1:3039
      - prefix: /static
        target: http://127.0.0.1:3039
  oauth-clients:
    "":
      clientId: "kubernetes-api-frontend"
      clientSecret: "secret"
      scopes:
        - openid
        - profile
        - email
      authorizeUrl: "http://localhost:8081/oauth/authorize"
      tokenUrl: "http://localhost:8081/oauth/token"
      introspectUrl: "http://localhost:8081/oauth/introspect"
      logoutUrl: "http://localhost:8081/oauth/logout"
    "bittokazi.com":
      clientId: "kubernetes-api-frontend"
      clientSecret: "secret"
      scopes:
        - openid
        - profile
        - email
      authorizeUrl: "http://localhost:8081/oauth/authorize"
      tokenUrl: "http://localhost:8081/oauth/token"
      introspectUrl: "http://localhost:8081/oauth/introspect"
      logoutUrl: "http://localhost:8081/oauth/logout"


idp-client-config:
  enabled: true
  end-point: http://localhost:8081
  client:
    clientId: "kubernetes-api-frontend"
    clientSecret: "secret"
